export const siteConfig = {
  name: "Somatic",
  shortName: "Somatic",
  logo: "android-chrome-512x512.png",
  description:
    "An AI-assisted healthcare platform connecting patients with first aid guidance, doctor consultations, lab tests, medical reports, medicines, insurance, and everyday healthcare services in one place.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  ogImage: "/og-image.png",
  authors: [
    {
      name: "Abhisek Dash",
      url: "https://github.com/Abhisek-Dash-Official/",
    },
  ],
  keywords: [
    "Somatic",
    "AI Healthcare",
    "AI-Assisted Healthcare",
    "Digital Healthcare",
    "Healthcare Platform",
    "HealthTech",
    "Patient Care",
    "Patient Portal",
    "Doctor Consultation",
    "Online Medical Consultation",
    "First Aid",
    "First Aid Guidance",
    "Emergency Healthcare",
    "Ambulance Assistance",
    "Nearby Hospital",
    "Hospital Discovery",
    "Lab Tests",
    "Home Sample Collection",
    "Medical Reports",
    "Medical Report Analysis",
    "Healthcare AI",
    "SOMA AI",
    "AI Health Assistant",
    "Symptom Analysis",
    "Health Education",
    "Medicine Delivery",
    "Blood Availability",
    "Healthcare Insurance",
    "Digital Insurance",
    "Health Payments",
    "Ayush Healthcare",
    "Ayurveda",
    "Ayurvedic Healthcare",
    "Rog Pariksha",
    "Dosha Analysis",
    "Vata Pitta Kapha",
    "Nadi Pariksha",
    "Clinical Documentation",
    "Doctor Dashboard",
    "Healthcare Management",
    "Digital Health",
  ],
};

export type SiteConfig = typeof siteConfig;
